baseurl = "https://drwave.netlify.com/"
languageCode = "en-us"
title = "MY BLOG DAWG"
googleAnalytics = ""
paginate = 10
#theme = "Intell-Analyst"

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    location = ""
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [wave](https://drwave.netlify.com/)."
    date_format = "2006-01-02"

[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
