name = "Wave"
license = "MIT"
licenselink = "https://drwave.netlify.com/"
description = "Hugo Themes Wave"
homepage = "https://github.com/echavi32"
tags = ["blog"]
features = ["wave", "bootstrap", "talaria", "font-awesome", "lunr.js", "bower", "particles.js", "createjs"]
min_version=0.15

[author]
  name = "echavi"
  homepage = "https://github.com/echavi32"

[original]
    author = "syui"
    homepage = "https://github.com/echavi32"
    repo = "https://github.com/echavi32"
