name = "Wave"
license = "MIT"
licenselink = "https://drwave.netlify.com/"
description = "Hugo Themes Wave"
homepage = "https://edwardchavis.netlify.com/"
tags = ["blog"]
features = ["wave", "bootstrap", "talaria", "font-awesome", "lunr.js", "bower", "particles.js", "createjs"]
min_version=0.15

[author]
  name = "syui"
  homepage = "https://syui.gitlab.io"

[original]
    author = "syui"
    homepage = "https://syui.github.io"
    repo = "https://github.com/syui/hugo-theme-arch"
